spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/oms
    username: root
    password: my-secret-pw
  jpa:
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true